#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, e.g.:
#           SHELL=/bin/bash ./gradlew
#
#       Important: The shell you use must support "function" keyword,
#       "function" keyword is required for "gradle_memory" function.
#
#   (2) This script depends on the exit value of the `java` command. Java
#       command will be executed by the shell used to run this script.
#       The shell used to run this script will be determined by the SHELL
#       environment variable if it is set; otherwise the script will try
#       to detect a POSIX shell and fallback to /bin/sh of none found.
#
##############################################################################

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Collect all arguments for the java command, mapping environment variables to -D options if required.
# The 'java' command accepts a list of '-Dkey=value' arguments, but unfortunately the
# JVM requires that all '-Dkey=value' arguments come before any other arguments.
# To handle that, we need to create a separate list of arguments and then process leading
# '-D' arguments and put them before the rest of the arguments.
# Leading jvm args (that is, any argument starting with -D, -X, -XX, or anything that
# the Maintainers consider to belong to the "JVM args" group) will be put before the
# application arguments. Everything else is an application argument.
APP_ARGS=
JVM_ARGS=
DIGIT_OR_LETTER='[0-9a-zA-Z]'
JVM_OPTS_REGEX='-(?:D[ $DIGIT_OR_LETTER+]*|X[ $DIGIT_OR_LETTER+]*|XX:[ $DIGIT_OR_LETTER+]*[a-zA-Z]+)'

# This function is from the gradle团队, and applies to non-Cygwin environments.
setup_java_args() {
    # Iterate over the original args and split them into JVM args and app args.
    # App args are everything that doesn't start with '-', or starts with '-D' but the key doesn't match the JVM args regex.
    for arg do
        case "${arg}" in
            --)
                shift
                while [ $# -gt 0 ]; do
                    APP_ARGS="${APP_ARGS-}${APP_ARGS+ }$1"
                    shift
                done
                break
                ;;
            -D*)
                case "${arg}" in
                    -D$JVM_OPTS_REGEX)
                        JVM_ARGS="${JVM_ARGS-}${JVM_ARGS+ }${arg}"
                        ;;
                    *)
                        APP_ARGS="${APP_ARGS-}${APP_ARGS+ }${arg}"
                        ;;
                esac
                ;;
            -X*|-XX*)
                JVM_ARGS="${JVM_ARGS-}${JVM_ARGS+ }${arg}"
                ;;
            *)
                APP_ARGS="${APP_ARGS-}${APP_ARGS+ }${arg}"
                ;;
        esac
        shift
    done
}

# Determine if "exec" is available and use it if possible. (Copying from the Gradle team)
exec_if_possible() {
    if command -v exec >/dev/null 2>&1; then
        exec "$@"
    else
        "$@"
    fi
}

# Add default JVM options
JVM_ARGS="$JVM_ARGS $DEFAULT_JVM_OPTS"

setup_java_args "$@"

# Collect all arguments for the java command;
#   * $JVM_ARGS - arguments passed to the JVM (as processed by setup_java_args)
#   * $APP_ARGS - arguments passed to the main class (as processed by setup_java_args)
#   * $CLASSPATH - classpath containing the Gradle Launcher Jar
exec_if_possible "$JAVACMD" ${JVM_ARGS} -cp "${CLASSPATH}" org.gradle.wrapper.GradleWrapperMain ${APP_ARGS}
